name: iptv_player
description: A starter Flutter application for macOS with macos_ui
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.5
  collection: ^1.16.0
  desktop_multi_window: ^0.2.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  go_router: ^6.5.8
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  macos_ui:
    git:
      url: https://github.com/macosui/macos_ui
      ref: dev
  #  media_kit: ^0.0.6                              # Primary package.
  #  media_kit_video: ^0.0.8                        # For video rendering.
  #  media_kit_native_event_loop: ^1.0.3            # Support for higher number of concurrent instances & better performance.           # iOS package for video native libraries.
  #  media_kit_libs_macos_video: ^1.0.4             # macOS package for video native libraries.
  media_kit:
    path: ../media_kit/media_kit
  media_kit_video:
    path: ../media_kit/media_kit_video
  media_kit_native_event_loop:
    path: ../media_kit/media_kit_native_event_loop
  media_kit_libs_macos_video:
    path: ../media_kit/media_kit_libs_macos_video
  media_kit_video_controls:
    path: ../media_kit/media_kit_video_controls
  m3u_parser_nullsafe: ^1.0.3
  riverpod_annotation: ^2.1.1
  path_provider: ^2.0.14
  platform_builder: ^3.0.0
  formz: ^0.6.0
  http: ^0.13.6
  intl: ^0.18.1
  window_manager: ^0.3.2
  fast_cached_network_image: ^1.2.0

dev_dependencies:
  build_runner:
  custom_lint:
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1
  riverpod_lint:
  riverpod_generator: ^2.2.1

dependency_overrides:
  media_kit:
    path: ../media_kit/media_kit
  media_kit_video:
    path: ../media_kit/media_kit_video
  media_kit_native_event_loop:
    path: ../media_kit/media_kit_native_event_loop
  media_kit_libs_macos_video:
    path: ../media_kit/media_kit_libs_macos_video
  media_kit_video_controls:
    path: ../media_kit/media_kit_video_controls

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
